FROM golang:1.23

WORKDIR /app

COPY ./log-redis-pusher/go.mod ./log-redis-pusher/go.sum ./

RUN go mod download

COPY ./log-redis-pusher/ .

RUN go build -o log-redis-pusher .

CMD ["./log-redis-pusher"]
