FROM golang:1.23.2

WORKDIR /app

COPY ./feed-api/go.mod ./feed-api/go.sum ./

RUN go mod download

COPY ./feed-api/ .

COPY ./feed-api/.env ./.env

RUN go build -o feed-api .

EXPOSE 8080

CMD ["./feed-api"]
