FROM golang:1.23.2

WORKDIR /app

COPY ./feed-curator/go.mod ./feed-curator/go.sum ./

RUN go mod download

COPY ./feed-curator/ .

# COPY ./feed-curator/.env ./.env

RUN go build -o feed-curator .

CMD ["./feed-curator"]
